In [106]:
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error, r2_score, mean_absolute_error

In [42]:
import math

In [43]:
df = pd.read_excel("NOTAS_COMPUTACAO.xlsx")

In [45]:
vocabulary = {
    "FIS101": 11, "MAT121": 12, "MAT131": 13, "QUI104": 14, "TEF101": 15, "EPB302": 16, "FIS102": 17,
    "GEO101": 18, "MAT122": 19, "MAT132": 20, "MAT141": 21, "QUI105": 22, "TEF102": 23, "FIS103": 24,
    "FIS111": 25, "GEO102": 26, "MAT123": 27, "MAT145": 28, "QUI142": 29, "GEO206": 30, "MAT146": 31,
    "MET201": 32, "MET211": 33, "QUI143": 34, "TEF133": 35, "TEF131": 36, "MET212": 37, "FIS104": 38,
    "MET225": 39, "TEF301": 40, "FIS112": 41, "QUI134": 42, "TEF107": 43, "MET226": 44, "TEF241": 45,
    "TEF121": 46, "COM148": 47, "COM152": 48, "EFD301": 49, "EFD302": 50, "EPB301": 51, "FIS201": 52,
    "MAT125": 53, "MAT134": 54, "MAT148": 55, "MAT152": 56, "COM146": 57, "COM149": 58, "EFD304": 59,
    "MAT126": 60, "MAT149": 61, "MAT150": 62, "COM141": 63, "COM211": 64, "COM230": 65, "EFD303": 66,
    "MAT127": 67, "MAT151": 68, "MAT211": 69, "MAT220": 70, "MAT230": 71, "EEG201": 72, "EEG231": 73,
    "QUI136": 74, "TEF215": 75, "COM213": 76, "COM214": 77, "COM321": 78, "COM323": 79, "FIS205": 80,
    "MAT213": 81, "MAT214": 82, "MAT321": 83, "COM153": 84, "COM231": 85, "COM311": 86, "COM322": 87,
    "COM326": 88, "COM343": 89, "FIS202": 90, "LET421": 91, "MAT153": 92, "COM217": 93, "COM232": 94,
    "COM312": 95, "COM325": 96, "COM328": 97, "MAT232": 98, "EEG202": 99, "EEG221": 100, "COM233": 101,
    "COM331": 102, "COM336": 103, "COM340": 104, "COM341": 105, "LET303": 106, "COM218": 107, "COM234": 108,
    "COM324": 109, "COM329": 110, "COM332": 111, "COM342": 112, "LET423": 113, "EEG222": 114, "MAT135": 115,
    "COM327": 116, "FIS210": 117, "GEO291": 118, "QUI113": 119, "COM346": 120, "COM347": 121, "FIS211": 122,
    "FIS213": 123, "GEO104": 124, "GEO110": 125, "QUI114": 126, "TEF104": 127, "TEF216": 128, "COM100": 129,
    "COM300": 130, "COM971": 131, "FIS216": 132, "GEO244": 133, "CIV251": 134, "COM101": 135, "COM301": 136,
    "COM600": 137, "COM800": 138, "COM102": 139, "COM601": 140, "COM801": 141, "DIR248": 142, "GEO207": 143,
    "GEO239": 144, "PRO241": 145, "PRO242": 146, "PRO243": 147, "PRO244": 148, "PRO249": 149, "CIV232": 150,
    "COM103": 151, "COM104": 152, "COM302": 153, "COM400": 154, "COM602": 155, "FIS208": 156, "GEO245": 157,
    "MTM112": 158, "MTM122": 159, "MTM123": 160, "MTM124": 161, "MTM125": 162, "MTM131": 163, "MTM151": 164,
    "TEF108": 165, "TEF217": 166, "COM105": 167, "COM200": 168, "COM500": 169, "COM603": 170, "COM622": 171,
    "COM721": 172, "COM821": 173, "COM921": 174, "GEO111": 175, "GEO132": 176, "GEO212": 177, "COM201": 178,
    "COM339": 179, "COM423": 180, "COM604": 181, "COM621": 182, "COM802": 183, "COM822": 184, "COM824": 185,
    "FIS209": 186, "FIS214": 187, "QUI147": 188, "CIV200": 189, "COM221": 190, "COM520": 191, "COM950": 192,
    "FIS212": 193, "QUI200": 194, "TEF109": 195, "CIC110": 196, "CIC131": 197, "COM624": 198, "COM626": 199,
    "COM951": 200, "COM952": 201, "CAT104": 202, "CAT108": 203, "CBI145": 204, "CIC111": 205, "COM338": 206,
    "COM421": 207, "COM522": 208, "QUI119": 209, "COM222": 210, "COM422": 211, "DIR501": 212, "DIR511": 213,
    "FIL200": 214, "FIS215": 215, "GEO227": 216, "QUI117": 217, "CIC101": 218, "CIC120": 219, "CIC130": 220,
    "CIC201": 221, "COM111": 222, "COM120": 223, "COM130": 224, "COM202": 225, "COM272": 226, "COM373": 227,
    "COM625": 228, "FIS611": 229, "CAT109": 230, "CAT141": 231, "CIC102": 232, "CIC170": 233, "CIC200": 234,
    "CIC210": 235, "CIC230": 236, "CIC271": 237, "CIC272": 238, "CIC273": 239, "CIC280": 240, "CIC370": 241,
    "PRO315": 242, "CIC100": 243, "CIC121": 244, "CIC180": 245, "CIC192": 246, "CIC211": 247, "CIC231": 248,
    "CIC240": 249, "CIC241": 250, "CIC260": 251, "CIC270": 252, "COM370": 253, "CIC220": 254, "CIC232": 255,
    "CIC242": 256, "CIC250": 257, "CIC261": 258, "CIC290": 259, "CIC361": 260, "CIC374": 261, "DIR752": 262,
    "EDU102": 263, "EDU301": 264, "LET411": 265, "PRO233": 266, "CAT151": 267, "CIC105": 268, "CIC233": 269,
    "CIC282": 270, "CIC342": 271, "CIC373": 272, "CIC390": 273, "MTM100": 274, "MTM175": 275, "MTM182": 276,
    "MUS003": 277, "MUS409": 278, "PRO229": 279, "PRO230": 280, "PRO302": 281, "CIC321": 282, "CIC340": 283,
    "CIC341": 284, "CIC360": 285, "CIC391": 286, "FIS314": 287, "FIS827": 288, "MTM102": 289, "MTM119": 290,
    "MTM120": 291, "MTM148": 292, "MTM188": 293, "PRO311": 294, "PRO397": 295, "CIC243": 296, "EDU303": 297,
    "FIL108": 298, "PRO101": 299, "PRO314": 300, "TUR117": 301, "TUR158": 302, "CIC333": 303, "CIC362": 304,
    "PRO320": 305, "PRO333": 306, "TUR307": 307, "CIC334": 308, "CIC344": 309, "EDU238": 310, "MTM109": 311,
    "MTM138": 312, "MTM139": 313, "MTM190": 314, "MTM492": 315, "CIC285": 316, "CIC335": 317, "CIC345": 318,
    "EDU236": 319, "MTM103": 320, "MTM130": 321, "MTM199": 322, "MTM493": 323, "TUR149": 324, "CEA300": 325,
    "CEA307": 326, "CEA425": 327, "CEA480": 328, "CEA420": 329, "CEA491": 330, "EDU237": 331, "MTM105": 332,
    "MTM135": 333, "MTM494": 334, "CEA421": 335, "CEA438": 336, "CEA481": 337, "CEA482": 338, "CIC320": 339,
    "MTM107": 340, "MTM212": 341, "CEA479": 342, "CIC107": 343, "CIC190": 344, "CIC336": 345, "CAT112": 346,
    "CIC103": 347, "CIC108": 348, "CEA144": 349, "CEA452": 350, "CEA467": 351, "CEA483": 352, "CEA484": 353,
    "CIC372": 354, "CEA101": 355, "CEA473": 356, "PRO232": 357, "PRO701": 358, "PRO703": 359, "CEA160": 360,
    "CEA412": 361, "CEA032": 362, "CEA419": 363, "CEA428": 364, "CEA429": 365, "CEA437": 366, "CEA440": 367,
    "CEA456": 368, "CEA460": 369, "CEA485": 370, "CEA150": 371, "FIS132": 372, "PRO235": 373, "PRO705": 374,
    "BCC101": 375, "BCC102": 376, "BCC201": 377, "BCC202": 378, "BCC203": 379, "BCC204": 380, "BCC221": 381,
    "BCC222": 382, "BCC241": 383, "BCC242": 384, "BCC243": 385, "BCC261": 386, "BCC262": 387, "BCC263": 388,
    "BCC321": 389, "BCC322": 390, "BCC323": 391, "BCC324": 392, "BCC326": 393, "BCC327": 394, "BCC341": 395,
    "BCC342": 396, "BCC362": 397, "BCC391": 398, "BCC422": 399, "BCC425": 400, "BCC446": 401, "BCC447": 402,
    "BCC449": 403, "BCC461": 404, "BCC466": 405, "CEA030": 406, "CEA145": 407, "EAD700": 408, "MTM242": 409,
    "MTM243": 410, "MTM244": 411, "MTM245": 412, "CEA422": 413, "BCC264": 414, "BCC265": 415, "BCC325": 416,
    "BCC361": 417, "BCC390": 418, "BCC444": 419, "BCC445": 420, "BCC448": 421, "BCC502": 422, "BCC701": 423,
    "BCC760": 424, "CEA450": 425, "CEA458": 426, "FIL101": 427, "MTM247": 428, "BCC266": 429, "BCC328": 430,
    "BCC402": 431, "BCC421": 432, "BCC423": 433, "BCC441": 434, "BCC443": 435, "BCC483": 436, "BCC485": 437,
    "CEA126": 438, "MTM116": 439, "CEA001": 440, "CEA031": 441, "BCC244": 442, "BCC428": 443, "BCC464": 444,
    "BCC482": 445, "BCC486": 446, "BCC501": 447, "BCC503": 448, "CEA127": 449, "EAD707": 450, "DIR249": 451,
    "BCC481": 452, "CEA341": 453, "EST002": 454, "EST202": 455, "FIS119": 456, "FIS305": 457, "FIS315": 458,
    "CEA578": 459, "BCC450": 460, "ENP153": 461, "LET966": 462, "MTM625": 463, "ARQ212": 464, "CEA488": 465,
    "FIS130": 466, "GEO113": 467, "PRO724": 468, "QUI153": 469, "TUR114": 470, "BEV118": 471, "BEV214": 472,
    "BCC465": 473, "EDU210": 474, "FIS306": 475, "FIS316": 476, "FIS502": 477, "BCC463": 478, "CEA036": 479,
    "CSI032": 480, "CSI443": 481, "CSI488": 482, "CEA423": 483, "CSI424": 484, "ENP150": 485, "EST300": 486,
    "MTM700": 487, "ARQ208": 488, "BCC103": 489, "CSI460": 490, "EST301": 491, "EST303": 492, "ARQ209": 493,
    "BEV175": 494, "BCC702": 495, "QUI244": 496, "BCC403": 497, "BCC406": 498, "BCC462": 499, "FIS304": 500,
    "BCC392": 501, "BCC393": 502, "BCC405": 503, "DIR260": 504, "BCC505": 505, "BCC408": 506, "BCC407": 507,
    "BCC409": 508, "ALI100": 509, "ALI101": 510, "ALI201": 511, "ALI309": 512, "AMB101": 513, "AMB110": 514,
    "ARQ101": 516, "ARQ113": 517, "ARQ122": 518, "ARQ205": 519, "ARQ225": 520, "ARQ700": 521, "ARQ702": 522,
    "ARQ703": 523, "ART361": 524, "ART435": 525, "ART501": 526, "ART507": 527, "ART540": 528, "ART570": 529,
    "BCC720": 530, "BCC722": 531, "BCC740": 532, "BEV269": 533, "CAD035": 534, "CAD042": 535, "CAD063": 536,
    "CAT110": 537, "CAT114": 538, "CAT115": 539, "CAT117": 540, "CAT123": 541, "CAT124": 542, "CAT148": 543,
    "CAT157": 544, "CAT163": 545, "CAT165": 546, "CAT167": 547, "CAT168": 548, "CAT175": 549, "CAT181": 550,
    "CBI199": 551, "CBI232": 552, "CEA003": 553, "CEA201": 554, "CEA443": 555, "CIC109": 556, "CIC132": 557,
    "CIV424": 558, "CPA001": 559, "CSA035": 560, "CSA123": 561, "CSI030": 562, "CSI102": 563, "CSI104": 564,
    "CSI105": 565, "CSI145": 566, "CSI202": 567, "CSI203": 568, "CSI403": 569, "CSI427": 570, "CSI433": 571,
    "CSI491": 572, "CSI548": 573, "CSI602": 574, "DIR056": 575, "DIR133": 576, "DIR250": 577, "DIR301": 578,
    "DIR503": 579, "DIR504": 580, "DIR701": 581, "DIR714": 582, "DIR717": 583, "DIR751": 584, "DIR760": 585,
    "DIR762": 586, "DIR802": 587, "EAD214": 588, "EAD344": 589, "EAD351": 590, "ECO004": 591, "EDU104": 592,
    "EDU106": 593, "EDU208": 594, "EDU212": 595, "EDU230": 596, "EDU515": 597, "EDU517": 598, "EDU519": 599,
    "EFD007": 600, "EFD009": 601, "EFD010": 602, "EFD011": 603, "EFD102": 604, "EFD110": 605, "EFD112": 606,
    "EFD113": 607, "EFD114": 608, "EFD115": 609, "EFD116": 610, "EFD118": 611, "EFD120": 612, "EFD126": 613,
    "EFD135": 614, "EFD136": 615, "EFD150": 616, "EFD151": 617, "EFD160": 618, "EFD162": 619, "EFD170": 620,
    "EFD174": 621, "EFD305": 622, "EFD308": 623, "EFD309": 624, "EFD310": 625, "EFD320": 626, "EFD344": 627,
    "EFD345": 628, "EFD346": 629, "EFD349": 630, "EFD353": 631, "ENP100": 632, "ENP144": 633, "ENP151": 634,
    "ENP473": 635, "EST001": 636, "EST005": 637, "EST009": 638, "EST201": 639, "EST203": 640, "EST306": 641,
    "FAR009": 642, "FAR401": 643, "FIL102": 644, "FIL107": 645, "FIL211": 646, "FIL491": 647, "FIL582": 648,
    "FIL600": 649, "FIL612": 650, "FIL643": 651, "FIS121": 652, "FIS131": 653, "FIS142": 654, "FIS309": 655,
    "FIS500": 656, "FIS830": 657, "GEO122": 658, "GEP023": 659, "GEP028": 660, "GEP106": 661, "GEP377": 662,
    "HIS115": 663, "HIS177": 664, "HIS300": 665, "HIS818": 666, "JOR223": 667, "LET041": 668, "LET100": 669,
    "LET112": 670, "LET309": 671, "LET314": 672, "LET422": 673, "LET544": 674, "LET545": 675, "LET741": 676,
    "LET742": 677, "LET856": 678, "LET903": 679, "LET955": 680, "LET956": 681, "LET957": 682, "MEC100": 683,
    "MEC101": 684, "MEC406": 685, "MED161": 686, "MED162": 687, "MED163": 688, "MED425": 689, "MET150": 690,
    "MET200": 691, "MET270": 692, "MIN100": 693, "MIN106": 694, "MIN110": 695, "MIN200": 696, "MSC025": 697,
    "MTM101": 698, "MTM110": 699, "MTM140": 700, "MTM163": 701, "MTM213": 702, "MTM246": 703, "MTM274": 704,
    "MTM280": 705, "MTM281": 706, "MTM283": 707, "MTM500": 708, "MTM601": 709, "MTM702": 710, "MTM730": 711,
    "MUL100": 712, "MUL101": 713, "MUL405": 714, "MUL440": 715, "MUL452": 716, "MUS013": 717, "MUS014": 718,
    "MUS130": 719, "MUS138": 720, "MUS153": 721, "MUS157": 722, "MUS203": 723, "MUS228": 724, "MUS255": 725,
    "MUS407": 726, "MUS458": 727, "MUS473": 728, "MUS488": 729, "MUS510": 730, "PRO034": 731, "PRO102": 732,
    "PRO106": 733, "PRO120": 734, "PRO126": 735, "PRO200": 736, "PRO201": 737, "PRO219": 738, "PRO224": 739,
    "PRO226": 740, "PRO227": 741, "PRO231": 742, "PRO237": 743, "PRO254": 744, "PRO255": 745, "PRO300": 746,
    "PRO301": 747, "PRO309": 748, "PRO312": 749, "PRO316": 750, "PRO318": 751, "PRO321": 752, "PRO325": 753,
    "PRO336": 754, "PRO343": 755, "PRO344": 756, "PRO366": 757, "PRO400": 758, "PRO404": 759, "PRO526": 760,
    "PRO600": 761, "PRO607": 762, "PRO702": 763, "PRO707": 764, "PRO710": 765, "PRO712": 766, "PRO713": 767,
    "PRO717": 768, "PRO718": 769, "PRO723": 770, "PRO807": 771, "PRO808": 772, "PRO900": 773, "PRO903": 774,
    "PRO905": 775, "PRO906": 776, "PRO907": 777, "PRO909": 778, "PRO920": 779, "QUI242": 780, "QUI243": 781,
    "QUI245": 782, "QUI701": 783, "SSO612": 784, "TEF219": 785, "TUR108": 786, "TUR112": 787, "TUR146": 788,
    "TUR151": 789, "TUR153": 790, "TUR164": 791, "TUR303": 792, "TUR304": 793, "TUR305": 794, "TUR306": 795,
    "TUR409": 796, "TUR421": 797, "TUR424": 798, "TUR425": 799, "TUR432": 800, "TUR433": 801, "TUR435": 802,
    "URB100": 803, "URB121": 804, "URB301": 805,  "ARQ100": 515
}

In [46]:
try:
    df = df.rename(columns={'CARATER ( obrigatória, eletiva e facultativa)': 'CARATER'})
except:
    print('coluna(s) não existe(m)' )

In [47]:
colunas = [
    #'ANO',
    #'SEMESTRE',
    'COD DISCIPLINA',
    'ALUNO',
    'CARATER',
    'MEDIA FINAL',
    'EXAME ESPECIAL',
    'FALTAS',
    #'SITUACAO'
] # SITUACAO foi ignorada por ser um lable que ja dá uma resposta de se o aluno foi aprovado ou não

df = df[colunas]

In [48]:
df['EXAME ESPECIAL'] = df['EXAME ESPECIAL'].notna().astype(int)

In [49]:
le_disc = LabelEncoder()
df['COD DISCIPLINA'] = df['COD DISCIPLINA'].map(vocabulary)
df['CARATER'] = le_disc.fit_transform(df['CARATER'])

Regressão linear

In [50]:
X = df.drop(columns=['MEDIA FINAL'])
y = df['MEDIA FINAL']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()


Random Forest Regressor

In [70]:
rf = RandomForestRegressor(
    n_estimators=450,
    max_depth=15,
    random_state=42,
    min_samples_leaf=5,
    max_features='sqrt',
    n_jobs=1
)

rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=15, max_features='sqrt', min_samples_leaf=5,
                      n_estimators=450, n_jobs=1, random_state=42)

Gradient Boosting Regressor

In [ ]:
gbr_1 = GradientBoostingRegressor( # usei de base
    loss='absolute_error',     
    n_estimators=500,
    learning_rate=0.055,
    max_depth=10,
    min_samples_leaf=10,
    subsample=0.8,
    random_state=42
    )

gbr_1.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.055, loss='absolute_error',
                          max_depth=10, min_samples_leaf=10, n_estimators=500,
                          random_state=42, subsample=0.8)

In [ ]:
gbr_2 = GradientBoostingRegressor( # max de 54.8%
    loss="squared_error",
    n_estimators=800,
    learning_rate=0.055,
    max_depth=7,
    min_samples_leaf=20,
    subsample=0.8,
    max_features="sqrt",
    random_state=42
    )

gbr_2.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.055, max_depth=7, max_features='sqrt',
                          min_samples_leaf=20, n_estimators=800,
                          random_state=42, subsample=0.8)

In [ ]:
gbr_3 = GradientBoostingRegressor( # max de 58.4%
    loss="squared_error",
    n_estimators=1000, # 1000 foi o mio 
    learning_rate=0.05, # 0.055 foi o mio
    max_depth=7,
    min_samples_leaf=20,
    subsample=0.8,
    random_state=42
)

gbr_3.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, max_depth=7, min_samples_leaf=20,
                          n_estimators=1000, random_state=42, subsample=0.8)

In [118]:
models = []

models.append(lr)
models.append(rf)
models.append(gbr_1)
models.append(gbr_2)
models.append(gbr_3)

Avaliação:

In [114]:
def avaliar(modelo, X_test, y_test):
    pred = modelo.predict(X_test)
    print(" RMSE:", root_mean_squared_error(y_test, pred))
    print(" R²:", r2_score(y_test, pred))
    print(" MAE:", mean_absolute_error(y_test, pred))


In [113]:
print("LR:")
avaliar(lr, X_test, y_test)
print("RF:")
avaliar(rf, X_test, y_test)
print("GBR 1:")
avaliar(gbr_1, X_test, y_test)
print("GBR 2:")
avaliar(gbr_2, X_test, y_test)
print("GBR 3:")
avaliar(gbr_3, X_test, y_test)

LR:
 RMSE: 3.2722690873214804
 R²: 0.14798468063045256
 MAE: 2.7466317419588924
RF:
 RMSE: 2.5157898569189507
 R²: 0.49638563672897207
 MAE: 1.9177009435437413
GBR 1:
 RMSE: 2.6206370560100742
 R²: 0.45353400832444324
 MAE: 1.7244137770050099
GBR 2:
 RMSE: 2.38324525520188
 R²: 0.5480536759772457
 MAE: 1.7902731943548003
GBR 3:
 RMSE: 2.2869543110395494
 R²: 0.5838361420774678
 MAE: 1.696737281402461


In [57]:
# Histórico do aluno
aluno_stats = df.groupby('ALUNO').agg({
    'MEDIA FINAL': 'mean',
    'FALTAS': 'mean'
}).rename(columns={
    'MEDIA FINAL': 'MEDIA ALUNO',
    'FALTAS': 'FALTAS ALUNO'
})

# Características da disciplina
disc_stats = df.groupby('COD DISCIPLINA').agg({
    'MEDIA FINAL': 'mean',
    'EXAME ESPECIAL': 'mean',
    'CARATER': 'mean'
}).rename(columns={
    'MEDIA FINAL': 'MEDIA DISCIPLINA',
    'EXAME ESPECIAL': 'TAXA EXAME'
})

In [58]:
def montar_features(aluno_id, cod_disciplina):
    #ALUNO	CARATER	MEDIA FINAL	EXAME ESPECIAL	FALTAS
    cod_enc = vocabulary.get(cod_disciplina)
    if cod_enc is None:
        return None  # disciplina desconhecida
    f = {}
    f['COD DISCIPLINA'] = cod_enc
    f['ALUNO'] = aluno_id
    f['CARATER'] = math.floor(disc_stats.loc[cod_enc, 'CARATER'])
    f['EXAME ESPECIAL'] = disc_stats.loc[cod_enc, 'TAXA EXAME']
    f['FALTAS'] = aluno_stats.loc[aluno_id, 'FALTAS ALUNO']

    return pd.DataFrame([f])

In [59]:
def recomendar(aluno, disciplinas, modelo, top_n=5):
    not_found = []
    preds = []
    for d in disciplinas:
        entrada = montar_features(aluno, d)
        if entrada is None:
            not_found.append(d)
            continue  # pula essa disciplina
        nota = modelo.predict(entrada)[0]
        preds.append((d, nota))

    return sorted(preds, key=lambda x: x[1], reverse=True)[:top_n], not_found

In [60]:
aluno_teste = 12

# disciplinas que o aluno AINDA NÃO cursou
disciplinas_candidatas = [
    'BCC328',
    'BCC222',
    'BCC333',
    'BCC444'
]

In [119]:
for model in models:
    print('--------#---------')
    print(model)
    recomendacoes, not_found = recomendar( aluno=aluno_teste, disciplinas=disciplinas_candidatas, modelo=model, top_n=3 ) 
    for d, nota in recomendacoes: 
        if nota >= 6.0: 
            print(f"Recomendada-se Disciplina: {d} | Nota prevista: {nota:.2f}")  
        else: 
            print(f"NÃO recomendada-se Disciplina: {d} | Nota prevista: {nota:.2f}")
        for d in not_found: 
            print(f"Disciplina {d} não encontrada")

--------#---------
LinearRegression()
Recomendada-se Disciplina: BCC444 | Nota prevista: 7.81
Disciplina BCC333 não encontrada
Recomendada-se Disciplina: BCC222 | Nota prevista: 7.19
Disciplina BCC333 não encontrada
Recomendada-se Disciplina: BCC328 | Nota prevista: 7.01
Disciplina BCC333 não encontrada
--------#---------
RandomForestRegressor(max_depth=15, max_features='sqrt', min_samples_leaf=5,
                      n_estimators=450, n_jobs=1, random_state=42)
Recomendada-se Disciplina: BCC328 | Nota prevista: 6.84
Disciplina BCC333 não encontrada
NÃO recomendada-se Disciplina: BCC444 | Nota prevista: 5.23
Disciplina BCC333 não encontrada
NÃO recomendada-se Disciplina: BCC222 | Nota prevista: 4.69
Disciplina BCC333 não encontrada
--------#---------
GradientBoostingRegressor(learning_rate=0.055, loss='absolute_error',
                          max_depth=10, min_samples_leaf=10, n_estimators=500,
                          random_state=42, subsample=0.8)
Recomendada-se Disciplina: BCC3

--------#---------
LinearRegression()
Recomendada-se Disciplina: BCC444 | Nota prevista: 7.81
Disciplina BCC333 não encontrada
Recomendada-se Disciplina: BCC222 | Nota prevista: 7.19
Disciplina BCC333 não encontrada
Recomendada-se Disciplina: BCC328 | Nota prevista: 7.01
Disciplina BCC333 não encontrada
--------#---------
RandomForestRegressor(max_depth=15, max_features='sqrt', min_samples_leaf=5,
                      n_estimators=450, n_jobs=1, random_state=42)
Recomendada-se Disciplina: BCC328 | Nota prevista: 6.84
Disciplina BCC333 não encontrada
NÃO recomendada-se Disciplina: BCC444 | Nota prevista: 5.23
Disciplina BCC333 não encontrada
NÃO recomendada-se Disciplina: BCC222 | Nota prevista: 4.69
Disciplina BCC333 não encontrada
--------#---------
GradientBoostingRegressor(learning_rate=0.055, loss='absolute_error',
                          max_depth=10, min_samples_leaf=10, n_estimators=500,
                          random_state=42, subsample=0.8)
Recomendada-se Disciplina: BCC328 | Nota prevista: 7.95
Disciplina BCC333 não encontrada
Recomendada-se Disciplina: BCC444 | Nota prevista: 6.14
Disciplina BCC333 não encontrada
NÃO recomendada-se Disciplina: BCC222 | Nota prevista: 5.88
Disciplina BCC333 não encontrada
--------#---------
GradientBoostingRegressor(learning_rate=0.055, max_depth=7, max_features='sqrt',
                          min_samples_leaf=20, n_estimators=800,
                          random_state=42, subsample=0.8)
NÃO recomendada-se Disciplina: BCC444 | Nota prevista: 5.71
Disciplina BCC333 não encontrada
NÃO recomendada-se Disciplina: BCC222 | Nota prevista: 5.23
Disciplina BCC333 não encontrada
NÃO recomendada-se Disciplina: BCC328 | Nota prevista: 5.22
Disciplina BCC333 não encontrada
--------#---------
GradientBoostingRegressor(learning_rate=0.05, max_depth=7, min_samples_leaf=20,
                          n_estimators=1000, random_state=42, subsample=0.8)
Recomendada-se Disciplina: BCC328 | Nota prevista: 6.54
Disciplina BCC333 não encontrada
Recomendada-se Disciplina: BCC444 | Nota prevista: 6.12
Disciplina BCC333 não encontrada
NÃO recomendada-se Disciplina: BCC222 | Nota prevista: 5.93
Disciplina BCC333 não encontrada